package com.tencent.angel.pytorch.utils

import com.tencent.angel.pytorch.utils

object Constants {
  /***
    * recommendation parameter constants
    */
  val TRAIN = "train"
  val PREDICT = "predict"
  val TRAIN_INPUT = "train_input"
  val VALIDATE_INPUT = "validate_input"
  val PREDICT_OUTPUT_PATH = "predict_output_path"
  val BATCH_SIZE = "batch_size"
  val LEARNING_RATE = "learning_rate"
  val OPTIMIZER = "optimizer"
  val TEST_RATIO = "test_ratio"
  val SAVE_PREDICTED_VECTOR = "save_predicted_vector"
  val EPOCH = "epoch"
  val DECAY = "decay"
  val ASYNC = "async"
  val MODEL_SAVE_PATH = "model_save_path"
  val MODEL_LOAD_PATH = "model_load_path"
  val SAVE_TORCH_MODEL = "save_torch_model"
  val ROW_TYPE = "row_type"
  val EVAL_METRICS = "eval_metrics"
  //calc feature importance, only support daw with "one-hot" field type for now
  val SAVE_FEAT_IMPORTANCE = "save_feat_importance"
  val SHUFFLE_INTERVAL = "shuffle_interval"
  val TDW_COLUMN_INDEX = "tdw_column_index"
  //calc validate loss means another forward computation on valid data, choose carefully
  val CALC_VALIDATE_LOSS = "calc_validate_loss"
  val DENSE_DIM = "dense_dim"
  val MODEL_SAVE_SUB_DIR = "/model"
  val TORCH_MODEL_SAVE_SUB_DIR = "/torch_model"
  val FEAT_IMPORTANCE_SAVE_SUB_DIR = "/feat_importance"
  val MODEL_FILE_SUFFIX = ".pt"
  val CONFIG_FILE_SUFFIX = ".yaml"
  val PYTHON_FILE_SUFFIX = ".py"
  val FILE_BASE_PATH = "./"
  val MODEL_NAME = "model_name"
  val PYTHON_ENV_MODEL_BASE_PATH = "./torch/pytorch/models/"
  val GEN_MODEL_TYPE_GRAPH = "graph"
  val GEN_MODEL_TYPE_RECOMMENDATION = "recommendation"

  /***
    * graph parameter constants
    */
  val GRAPH_TYPE_HOMOGENEOUS = "homogeneous"
  val GRAPH_TYPE_HETEROGENEOUS = "heterogeneous"
  val GRAPH_TYPE_BIPARTITE = "bipartite"
  val TASK_TYPE_SUPERVISED = "supervised"
  val TASK_TYPE_UNSUPERVISED = "unsupervised"
  val SAMPLE_NUM = "sample_num"
  val USER_SAMPLE_NUM = "user_sample_num"
  val ITEM_SAMPLE_NUM = "item_sample_num"
  val BATCH_INIT_BUM = "batch_init_num"
  val PERIODS = "periods"
  val CHECKPOINT_INTERVAL = "checkpoint_interval"
  val SAVE_MODEL_INTERVAL = "save_model_interval"
  val MULTI_HOT_FIELD = "multi_hot_field"
  val VALIDATE_PERIODS = "validate_periods"
  val SECOND_ORDER= "second"
  val USE_SHARED_SAMPLES = "use_shared_samples"
  val SAVE_CHECKPOINT = "save_checkpoint"
  val BATCH_SIZE_MULTIPLIER = "batch_size_multiplier"
  val SAMPLE_METHOD = "sample_method"
  val EVALUATION_RATIO = "evaluation_ratio"
  val THREADS_NUM = "threads_num"
  val PARALLEL_TRAIN = "parallel_train"
  val FEAT_EMBEDDING_LOAD_PATH = "feat_embedding_load_path"
  val NODE_EMBEDDING_OUTPUT_PATH = "node_embedding_output_path"
  val CONTEXT_EMBEDDING_LOAD_PATH = "context_embedding_load_path"
  val TEST_EDGE_PATH = "test_edge_path"
  val WALK_PATH = "walk_path"
  val NODE_TYPE_PATH = "node_type_path"
  val WINDOW_SIZE = "window_size"
  val NEGATIVE_SAMPLE_NUM = "negative_sample_num"
  val LOG_STEP = "log_step"
  val MEAN = "mean"
  val STD = "std"
  val NEGATIVE_SAMPLE_BY_NODE_TYPE = "negative_sample_by_node_type"
  val EVALUATE_BY_EDGE_TYPE = "evaluate_by_edge_type"
  val OUTPUT_EMBEDDING_BY_NODE_TYPE = "output_embedding_by_node_type"
  val OUTPUT_EMBEDDING_BY_EDGE_TYPE = "output_embedding_by_edge_type"
  val LABELS_NUM = "labels_num"
  val INPUT_DIM = "input_dim"
  val INPUT_EDGE_DIM = "input_edge_dim"
  val EMBEDDING_DIM = "embedding_dim"
  val INPUT_EMBEDDING_DIM = "input_embedding_dim"
  val INPUT_FIELD_NUM = "input_field_num"
  val INPUT_SPLIT_IDX = "input_split_idx"
  val NEG_SAMPLING = "neg_sampling"
  val DELIMITER = "sep"
  val WEIGHTED = "weighted"
  val EDGE_TIMESTAMP = "edge_timestamp"
  val FORMAT = "format"
  val PATH = "path"
  val VALIDATE_PATH = "validate_path"
  val SRC = "src"
  val DST = "dst"
  val INPUT_USER_DIM = "input_user_dim"
  val INPUT_ITEM_DIM = "input_item_dim"
  val INPUT_USER_EMBEDDING_DIM = "input_user_embedding_dim"
  val INPUT_USER_FIELD_NUM = "input_user_field_num"
  val INPUT_ITEM_EMBEDDING_DIM = "input_item_embedding_dim"
  val INPUT_ITEM_FIELD_NUM = "input_item_field_num"
  val INPUT_EDGE_EMBEDDING_DIM = "input_edge_embedding_dim"
  val INPUT_EDGE_FIELD_NUM = "input_edge_field_num"
  val USER_INPUT_SPLIT_IDX = "user_input_split_idx"
  val ITEM_INPUT_SPLIT_IDX = "item_input_split_idx"
  val EDGE_INPUT_SPLIT_IDX = "edge_input_split_idx"
  val INDEPENDENT_FIELD = "independent_field"
  val ENCODE = "encode"
  val TRAIN_SAMPLE_RATIO = "train_sample_ratio"
  val FILTER_SAME_NODE = "filter_same_node"
  val KEY_NODE = "key_node"
  val NODES_SAMPLE_NUM = "nodes_sample_num"
  val SUB_GRAPH_SAMPLE_NUM = "sub_graph_sample_num"
  val TASK_TYPE = "task_type"
  val INIT_METHOD = "init_method"
  val ITEM_TYPES = "item_types"
  val M = "m"
  val HOPS = "hops"
  val USE_WEIGHTED_AGGREGATE = "use_weighted_aggregate"
  val SAVE_CONCAT_FEATS = "save_concat_feats"
  val EDGE_TYPES = "edge_types"
  val NODE_TYPES = "node_types"
  val FFN_HIDDEN_SIZE = "ffn_hidden_size"
  val LAYERS = "layers"
  val AGGREGATION_TYPE = "aggregation_type"
  val SHUFFLE_SAMPLES = "shuffle_samples"
  val AUGMENTER = "augmenter"
  val AUGMENT_RATIO = "augment_ratio"
  val IS_OPTIMIZE = "is_optimize"
  val CONV = "conv"
  val PARTITION_OPT = "partition_opt"
  val LOCAL_NEGATIVE_SAMPLE = "local_negative_sample"
  val CHECK_OUTPUT = "check_output"
}

object SampleMethod extends Enumeration {
  type SampleMethod = Value
  val RANDOM: utils.SampleMethod.Value = Value("random")
}
