<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>com.tencent.angel</groupId>
    <artifactId>pytorch-on-angel</artifactId>
    <version>0.4.0</version>
    <relativePath>../pom.xml</relativePath>
  </parent>

  <artifactId>pytorch-on-angel-mllib</artifactId>
  <properties>
    <main.basedir>${project.parent.basedir}</main.basedir>
  </properties>

  <dependencies>
    <dependency>
      <groupId>it.unimi.dsi</groupId>
      <artifactId>fastutil</artifactId>
      <version>8.2.2</version>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>com.tencent.angel</groupId>
      <artifactId>spark-on-angel-mllib</artifactId>
      <version>${angel.version}</version>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>com.tencent.angel</groupId>
      <artifactId>spark-on-angel-graph</artifactId>
      <version>${angel.version}</version>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>com.tencent.angel</groupId>
      <artifactId>angel-ps-graph</artifactId>
      <version>${angel.version}</version>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>org.yaml</groupId>
      <artifactId>snakeyaml</artifactId>
      <version>1.16</version>
    </dependency>
    <dependency>
      <groupId>org.codehaus.groovy</groupId>
      <artifactId>groovy-all</artifactId>
      <version>2.4.7</version>
    </dependency>
  </dependencies>

  <build>
    <plugins>
      <plugin>
        <groupId>com.alexkasko.maven</groupId>
        <artifactId>jni-headers-maven-plugin</artifactId>
        <version>1.0.6</version>
        <executions>
          <execution>
            <id>javah</id>
            <phase>compile</phase>
            <goals>
              <goal>javah</goal>
            </goals>
            <configuration>
              <javahClass>com.tencent.angel.pytorch.Torch</javahClass>
              <javahOutputFilePath>${project.basedir}/jni/angel/pytorch/angel_torch.h</javahOutputFilePath>
            </configuration>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>

</project>